dist: xenial
language: shell
os: linux

# easy way to get your local config: cat ${HOME}/.kube/config | base64 | pbcopy
env:
  global:
    - DOCKER_PUBLIC_USERNAME=${DOCKER_PUBLIC_USERNAME:-openstad}
    - DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME:-frontend}
    - DEV_RELEASE_BRANCHES=${DEV_RELEASE_BRANCHES:-^development}
    - ACC_RELEASE_BRANCHES=${ACC_RELEASE_BRANCHES:-^staging}
    - PROD_RELEASE_BRANCHES=${PROD_RELEASE_BRANCHES:-^master$}
    - K8S_DEPLOYMENT_NAME=openstad-frontend
    - K8S_NAMESPACE=openstad
    - FRONTED_PORT=4444
    - FRONTEND_MONGO_SCHEME=mongodb://mongo
    - FRONTEND_MONGO_DB_HOST=mongo
    - FRONTEND_MONGO_PORT=27017
    - FRONTEND_MINIFY_JS=ON
    - COOKIE_SECURE_OFF=yes
    - API=http://localhost:8111
    - IMAGE_API_URL=http://localhost:3333
    - IMAGE_API_ACCESS_TOKEN=xxxx
    - IMAGE_API_ACCESS_TOKEN=xxxx
    - SITE_API_KEY=xxxx
    - DEFAULT_DB=localhost2
    - DEFAULT_HOST=localhost:4444
    - APP_URL=http://localhost:4444
    - HELM_REPO_NAME=openstad-kubernetes
    - HELM_CHART_FOLDER=k8s/openstad

services:
  - docker

addons:
  snaps:
    – yq

before_install:
  - echo ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
  - echo ${DEV_RELEASE_BRANCHES}
  - docker build -t ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} .

script:
  - docker run -e CI=true ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}  npm run test -- --coverage
  - docker-compose -f docker-compose.travis.yml run frontend node apostrophe.js apostrophe:generation

stages:
  - name: docker_push
    if: branch = master
  - name: docker_push_tag
    if: tag IS present
  - name: kubectl_deploy
    if: env(KUBE_DEPLOY) IS present AND branch =~ env(PROD_RELEASE_BRANCHES)
  - name: gitops_dev
    if: env(GITOPS) IS present AND branch =~ env(DEV_RELEASE_BRANCHES)
  - name: gitops_dev
    if: env(GITOPS) IS present AND tag IS present

jobs:
  include:
    - stage: docker_push_tag
      name: 'Push new image with tag to docker'
      env:
        - IMAGE_TAG=${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
      script: bash docker_publish_tag
    - stage: docker_push
      name: 'Publish new docker image'
      script: bash docker_publish
    - stage: kubectl_deploy
      name: "Deploy: Kubectl set image"
      script: bash docker_deploy
    - stage: gitops_dev
      name: "Release and commit new image tag"
      env:
        - IMAGE_TAG=${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
        - GITOPS_VALUES_FILE=k8s/openstad/environments/dev.values.yaml
        - GITOPS_RELEASE_BRANCH=develop
      script: bash gitops_push
    - stage: gitops_tag
      name: "Release and commit new image tag"
      env:
        - IMAGE_TAG=${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_TAG}
        - GITOPS_VALUES_FILE=k8s/openstad/environments/prod.values.yaml
        - GITOPS_RELEASE_BRANCH=master
      script: bash gitops_push

