sudo: required
dist: xenial
language: minimal

# easy way to get your local config: cat ${HOME}/.kube/config | base64 | pbcopy
env:
  global:
    - DOCKER_PUBLIC_USERNAME=openstad
    - DOCKER_IMAGE_NAME=frontend
    - K8S_DEPLOYMENT_NAME=openstad-frontend
    - K8S_NAMESPACE=openstad
    - FRONTED_PORT=4444
    - FRONTEND_MONGO_SCHEME=mongodb://mongo
    - FRONTEND_MONGO_DB_HOST=mongo
    - FRONTEND_MONGO_PORT=27017
    - FRONTEND_MINIFY_JS=ON
    - COOKIE_SECURE_OFF=yes
    - API=http://localhost:8111
    - IMAGE_API_URL=http://localhost:3333
    - IMAGE_API_ACCESS_TOKEN=xxxx
    - IMAGE_API_ACCESS_TOKEN=xxxx
    - SITE_API_KEY=xxxx
    - DEFAULT_DB=localhost2
    - DEFAULT_HOST=localhost:4444
    - APP_URL=http://localhost:4444
    - HELM_REPO_NAME=openstad-kubernetes
    - HELM_CHART_FOLDER=k8s/openstad
    - GITOPS_VALUES_FILE=k8s/openstad/environments/dev.values.yaml

services:
  - docker

addons:
  snaps:
    – yq

before_install:
  - docker build -t ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} .

script:
  - docker run -e CI=true ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}  npm run test -- --coverage
  - docker-compose -f docker-compose.travis.yml run frontend node apostrophe.js apostrophe:generation

stages:
  - name: docker_push
    if: branch = master
  - name: docker_push_tag
    if: tag IS present
  - name: kubectl_deploy
    if: env(KUBE_DEPLOY) IS present AND branch IN (env(RELEASE_BRANCHES))
  - name: gitops
    if: env(GITOPS) IS present AND branch IN (env(RELEASE_BRANCHES))

jobs:
  include:
    - stage: docker_push_tag
      name: 'Push new image with tag to docker'
      env:
        - IMAGE_TAG=${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
      script: bash docker_publish_tag
    - stage: docker_push
      name: 'Publish new docker image'
      env:
        - IMAGE_TAG=${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
      script: bash docker_publish
    - stage: gitops
      name: "Release and commit new image tag"
      env:
        - IMAGE_TAG=${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
      script: bash gitops_push
    - stage: kubectl_deploy
      name: "Deploy: Kubectl set image"
      script: bash docker_deploy
