name: GitopsDev

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - development
      - feature/*

jobs:
  gitops:
    environment: gitops_dev
    env:
      HELM_REPO_NAME: openstad-kubernetes
      HELM_CHART_FOLDER: k8s/openstad
      GIT_USER_EMAIL: github@ci.push
      GIT_USER_NAME: "${{ secrets.GIT_USER_NAME }}"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      HELM_REPO: ${{ secrets.HELM_REPO }}
      HELM_REPO_WITH_TOKEN: ${{ secrets.HELM_REPO_WITH_TOKEN }}
      GITOPS_RELEASE_BRANCH: ${{ secrets.GITOPS_RELEASE_BRANCH }}
      SHORT_SHA: $(echo ${{ git.sha }} | cut -c 1-8)

    name: gitops commit
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq
        run: sudo snap install yq --channel=v3/stable

      - name: Run build script
        run: |
          sudo chmod a+x ./build.sh
          ./build.sh
        shell: bash
        env:
          IMAGE_TAG: ${{ secrets.DOCKER_PUBLIC_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.SHORT_SHA }}
      - name: Run docker push script
        run: |
          sudo chmod a+x ./gitops_push
          ./gitops_push
        shell: bash
        env:
          IMAGE_TAG: ${{ secrets.DOCKER_PUBLIC_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.SHORT_SHA }}
          GITOPS_VALUES_FILE: k8s/openstad/environments/dev.values.yaml
