name: GitopsDev

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - development
      - feature/*
      - release/*

jobs:
  gitops:
    environment: gitops_dev
    env:
      HELM_REPO_NAME: openstad-kubernetes
      HELM_CHART_FOLDER: k8s/openstad
      GIT_USER_EMAIL: github@ci.push
      GIT_USER_NAME: GitHub
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      HELM_REPO: ${{ secrets.HELM_REPO }}
      HELM_REPO_WITH_TOKEN: ${{ secrets.HELM_REPO_WITH_TOKEN }}
      GITOPS_RELEASE_BRANCH: ${{ secrets.GITOPS_RELEASE_BRANCH }}
      FRONTED_PORT: 4444
      FRONTEND_MONGO_SCHEME: mongodb://mongo
      FRONTEND_MONGO_DB_HOST: mongo
      FRONTEND_MONGO_PORT: 27017
      FRONTEND_MINIFY_JS: ON
      COOKIE_SECURE_OFF: yes
      API: http://localhost:8111
      IMAGE_API_URL: http://localhost:3333
      IMAGE_API_ACCESS_TOKEN: xxxx
      SITE_API_KEY: xxxx
      DEFAULT_DB: localhost2
      DEFAULT_HOST: localhost:4444
      APP_URL: http://localhost:4444
      APOS_BUNDLE: assets
      APOS_MINIFY: 1
      NODE_ENV: production
      BRANCH_REF: ${{ github.ref }}

    name: gitops commit
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq
        run: sudo snap install yq --channel=v3/stable

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Run build script
        run: |
          sudo chmod a+x ./build.sh
          ./build.sh
        shell: bash
        env:
          IMAGE_TAG: ${{ secrets.DOCKER_PUBLIC_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}

      - name: Run docker push script
        run: |
          sudo chmod a+x ./gitops_push
          ./gitops_push
        shell: bash
        env:
          IMAGE_TAG: ${{ secrets.DOCKER_PUBLIC_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}-${{ github.run_id}}
          GITOPS_VALUES_FILE: k8s/openstad/environments/dev.values.yaml
